.github/workflows/test.yml
package-lock.json
package.json
packages/sdk-core/src/model/report/BacktraceReport.ts
tsconfig.base.json

* Adds a job to GitHub test workflows which tests on Node 14.
* Changes Typescript target to ES2020 - Node 14 supports it according to https://node.green/
* Updates `error.cause` code, because Typescript does not detect it prior to ES2022

Add support for Node 14.

---

packages/browser/src/BacktraceClient.ts
packages/browser/src/agentDefinition.ts
packages/browser/src/builder/BacktraceClientBuilder.ts
packages/browser/tests/client/clientTests.spec.ts
packages/node/src/BacktraceClient.ts
packages/node/src/agentDefinition.ts
packages/node/src/builder/BacktraceClientBuilder.ts
packages/node/tests/client/clientTests.spec.ts
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
packages/sdk-core/src/builder/SdkOptions.ts
packages/sdk-core/src/common/IdGenerator.ts
packages/sdk-core/src/common/TimeHelper.ts
packages/sdk-core/src/index.ts
packages/sdk-core/src/model/data/BacktraceData.ts
packages/sdk-core/src/model/report/BacktraceReport.ts
packages/sdk-core/src/modules/converter/AttributeConverter.ts
packages/sdk-core/src/modules/converter/ReportConverter.ts
packages/sdk-core/src/modules/data/AttributeAndAnnotationBuilder.ts
packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
packages/sdk-core/tests/client/clientTests.spec.ts
packages/sdk-core/tests/converters/attributeConverterTests.spec.ts
packages/sdk-core/tests/mocks/BacktraceTestClient.ts
packages/sdk-core/tests/report/dataGenerationTests.spec.ts

This diff connects all logic from the previous pull requests together to send report to Backtrace! In this diff you can find a:
* Builder definition
* Report generation logic
Goal: create a client and send a basic backtrace report to Backtrace.

Use factory to generate client and send report to Backtrace

---

build/agentDefinitionPlugin.js
build/common.js
packages/sdk-core/src/common/IdGenerator.ts

This code is necessary for both browser and node packages to be built with Webpack.
The `IdGenerator` change is necessary to remove the `crypto` dependency, which is not possible to resolve in the browser package.

Add common stuff necessary for Webpack in browser and node.

---

package-lock.json
package.json
tools/sourcemap-tools/LICENSE
tools/sourcemap-tools/jest.config.js
tools/sourcemap-tools/package.json
tools/sourcemap-tools/src/ContentAppender.ts
tools/sourcemap-tools/src/DebugIdGenerator.ts
tools/sourcemap-tools/src/index.ts
tools/sourcemap-tools/tests/ContentAppender.spec.ts
tools/sourcemap-tools/tests/DebugIdGenerator.spec.ts
tools/sourcemap-tools/tsconfig.json
tsconfig.json
tsconfig.packages.json

This PR adds `sourcemap-tools` package with `DebugIdGenerator` and `ContentAppender` classes to help create future plugins for working with sourcemaps.
Specific usage will be shown in the next PR with the Webpack plugin.

Add helpers for future sourcemap plugins and CLI.

---

packages/browser/src/converters/JavaScriptCoreStackTraceConverter.ts
packages/browser/src/converters/SpiderMonkeyStackTraceConverter.ts
packages/browser/tests/converters/javascriptCore/javaScriptCoreStackTraceConverterTests.spec.ts
packages/browser/tests/converters/spiderMonkey/spiderMonkeyStackTraceConverterTests.spec.ts
packages/sdk-core/src/modules/converter/BacktraceStackTraceConverter.ts
packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
packages/sdk-core/tests/converters/stackTraceConverterTests.spec.ts

This removes the necessity to pass the whole `BacktraceReport` to the stack trace converters.

Make stack trace converter simpler by requiring only stack trace and message

---

package-lock.json
tools/sourcemap-tools/package.json
tools/sourcemap-tools/src/DebugIdGenerator.ts
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/src/helpers/bytesToUuid.ts
tools/sourcemap-tools/src/helpers/stringToUuid.ts
tools/sourcemap-tools/src/index.ts
tools/sourcemap-tools/tests/SourceMapProcessor.spec.ts
tools/sourcemap-tools/tests/SourceProcessor.spec.ts

When testing Webpack output with potential SDK changes, I've stumbled upon an error - source snippets adding debug IDs may have been executed later than the report was created, thus breaking the whole debug ID idea.
So I've opted to add them to the beginning of the file. This, however, breaks the sourcemaps, because a new line is added and all mappings are now offset.
I have decided to create a bundler-agnostic solution that appends the necessary code, and then fixes the sourcemaps. Webpack changes will be added in the next PR.

Add `SourceProcessor` class

---

packages/sdk-core/src/model/http/BacktraceReportSubmission.ts
packages/sdk-core/src/model/http/SubmissionUrlInformation.ts
packages/sdk-core/src/model/http/index.ts
packages/sdk-core/src/modules/metrics/MetricsUrlInformation.ts
packages/sdk-core/tests/http/submissionUrlGenerationTests.spec.ts
packages/sdk-core/tests/http/tokenTests.spec.ts
packages/sdk-core/tests/http/universeTests.spec.ts

In our submission URLs we have a lot of important information. We should continue using them but also reuse information from them in other places of the SDK - for example, to learn what is the user universe name or the submission token. 
This diff adds URL parsers to javascript SDK

Submission URL parser

---

package-lock.json
tools/webpack-plugin/.gitignore
tools/webpack-plugin/package.json
tools/webpack-plugin/src/BacktracePlugin.ts
tools/webpack-plugin/src/helpers/statsPrinter.ts
tools/webpack-plugin/src/models/AssetStats.ts
tools/webpack-plugin/webpack.config.js

This PR adds a summary of modified and uploaded files at the end of the compilation.

Add printing asset stats to Webpack plugin

---

packages/browser/src/BacktraceClient.ts
packages/node/src/BacktraceClient.ts
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/index.ts
packages/sdk-core/src/model/data/BacktraceStackTrace.ts
packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
packages/sdk-core/src/sourcemaps/DebugIdProvider.ts
packages/sdk-core/src/sourcemaps/VariableDebugIdMapProvider.ts
packages/sdk-core/src/sourcemaps/index.ts
packages/sdk-core/src/sourcemaps/interfaces/DebugIdMapProvider.ts
packages/sdk-core/tests/report/dataGenerationTests.spec.ts

This PR adds support for debug IDs in previously built files.
How it works:
1. debug IDs are being injected while building the files using for example a Webpack plugin
2. when creating a report, debug IDs are loaded using `DebugIdProvider`:
1. debug IDs are being retrieved using `DebugIdMapProvider` - in node and browser using `VariableDebugIdMapProvider` from `global` and `window`, respectively,
2. first frame's library from each file's stack and debug ID are saved
3. the debug IDs are assigned to each frame to `debug_identifier` property where a debug ID for library exists

Add debug IDs support to sdk-core, node and browser packages

---

package-lock.json
packages/browser/src/index.ts
packages/react/jest.config.js
packages/react/package.json
packages/react/src/BacktraceClient.ts
packages/react/src/ErrorBoundary.tsx
packages/react/src/index.ts
packages/react/tests/errorBoundaryTests.spec.tsx
packages/react/tsconfig.json

Adding:
- A React BacktraceClient
- Adding a custom Backtrace ErrorBoundary that sends a report to Backtrace on a rendering error
- Tests
You will also see that I added an initialize() function to the React BacktraceClient. I needed this to add the client to the window but I also propose that we add an initialize function to all of our BacktraceClients as I find it to be a good user experience and not require the user to know about implementation details.

Adding React Backtrace Client, ErrorBoundary, and tests

---

packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/modules/attribute/ClientAttributeProvider.ts

To make agent name queryable in Backtrace, I've added `backtrace.agent` as an additional attribute aside `backtrace.version`.

Add 'backtrace.agent' attribute specifying submitting agent name

---

package-lock.json
tools/cli/package.json
tools/cli/src/helpers/find.ts

This PR adds the possibility of using glob patterns in the CLI, for example:
```
backtrace-js add-sources ./dir1/**/lib ./dir2/**/**/dir3`
```

Add glob patterns for finding files in CLI.

---

tools/cli/package.json
tools/cli/src/index.ts

This adds `backtrace-js` as a bin entry to enable using `backtrace-js` in the shell.

Add bin entry to CLI.

---

packages/sdk-core/src/model/data/BacktraceData.ts
packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts

This diff adds the symbolication type to the backtrace data object. By doing that, the backend can start using source maps to adjust stack trace

Include symbolication in the diagnostic error object

---

packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
packages/sdk-core/tests/client/attributesTests.spec.ts
packages/sdk-core/tests/client/clientCallbacksTests.spec.ts
packages/sdk-core/tests/client/clientTests.spec.ts
packages/sdk-core/tests/mocks/BacktraceTestClient.ts

This diff adds before send event to the client. We're trying to be consistent between different clients and SDKs that we offer. All our managed SDKs offer "before send" event to modify data or even skip sending it for any reason. Why do customers want to use it?
- based on dynamic criteria, decide to not send it
- apply PII settings 
- apply custom attribute logic when error happen

Before send event support

---

tools/sourcemap-tools/src/SourceProcessor.ts

* Fixes issue when sourcemap does not have the `sources` array or it is `null`.

sourcemap tools: fix doesSourceMapHaveSources with undefined sources

---

tools/cli/src/sourcemaps/upload.ts

If `--include-sources` is not passed to the `upload` command, the sources will be stripped from the sourcemap before uploading.

cli: add stripping sourcesContent by default

---

packages/browser/src/BacktraceClient.ts
packages/browser/src/breadcrumbs/DocumentEventSubscriber.ts
packages/browser/src/breadcrumbs/HistoryEventSubscriber.ts
packages/browser/src/breadcrumbs/WebRequestEventSubscriber.ts
packages/browser/src/builder/BacktraceClientBuilder.ts
packages/react/src/builder/BacktraceReactClientBuilder.ts
packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts
packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts

This diff adds browser/react breadcrumbs support. Right now we support: 
- console.log breadcrumbs
- HTTP requests
- user actions
- navigation events

Browser breadcrumbs support

---

package-lock.json
tools/cli/package.json
tools/cli/src/commands/Command.ts
tools/cli/src/helpers/jsonc.ts
tools/cli/src/helpers/normalizePaths.ts
tools/cli/src/helpers/version.ts
tools/cli/src/index.ts
tools/cli/src/options/loadOptions.ts
tools/cli/src/options/models/CliOptions.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/process.ts
tools/cli/src/sourcemaps/upload.ts

* `--version` option
* Additional messages about missing files for processing/upload/adding sources
* Add `.backracejsrc` file support, which enables configuration of every command line option, for example:
```jsonc
{
// Supports comments!
"path": "global path",
"add-sources": {
"path": "add-sources specific path"
},
"upload": {
"url": "url for uploading"
}
}
```

cli: quality of life improvements

---

packages/node/src/database/BacktraceDatabaseFileRecord.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/database/model/BacktraceDatabaseRecord.ts
packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
packages/sdk-core/tests/database/databaseSendTests.spec.ts
packages/sdk-core/tests/mocks/testStorageProvider.ts

This diff adds database operations to the offline database. In some situations, our customers need to be fully offline or want to send data only when something happens (for example: to not impact the application performance). In this situation our users would rather add to the database, not send them immediately. To provide full offline support we need to give our customers an option to send manually reports. 
This diff adds basic database send operations that allow to:
* send reports with respect of retry settings
* flush the database - send and forget.

Database send operations

---

packages/browser/src/BacktraceClient.ts
packages/node/src/BacktraceClient.ts
packages/react/src/BacktraceClient.ts
packages/react/src/ErrorBoundary.tsx
packages/sdk-core/src/BacktraceCoreClient.ts

We can only have one crash-reporting solution available in the application created/spawned by us! In addition to that, if someone initialize the client once again, we might have a race condition between Backtrace Database instances. To avoid those problems the initialize method caches now the instance. With this change we know there is only one existing instance of the client. 
We still leave an option to create a backtrace client by the super user if there is a use case and benefit from doing that.

Allow to use only one client via user-friendly API

---

packages/sdk-core/src/sourcemaps/DebugIdProvider.ts

This diff allows to handle a situation when the debugId is not present because of the dynamic import executed after the application startup.

Lazy load debug ids

---

packages/browser/src/index.ts
packages/node/src/index.ts
packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
packages/sdk-core/src/modules/breadcrumbs/index.ts
packages/sdk-core/src/modules/breadcrumbs/model/RawBreadcrumb.ts
packages/sdk-core/src/modules/breadcrumbs/storage/BreadcrumbsStorage.ts
packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsInterceptorTests.spec.ts

In the case of breadcrumbs containing PII information that needed to be filtered out, now we allow users to modify breadcrumb or remove it. 
Right now users can remove any content of the breadcrumb or modify it to their needs.

Breadcrumb interceptor

---

packages/sdk-core/src/common/textFormatter.ts
packages/sdk-core/src/modules/breadcrumbs/events/ConsoleEventSubscriber.ts

The breadcrumbs integration uses the util format method to format all console parameters. Util is the library available in the web browser or in node. However there is a chance the library won't be available in the sandbox env like in react-native. This diff adds a fallback function to format console logs when the util function is not available

Fallback to default log function if the util function is not available

---

packages/browser/src/engineDetector.ts

This diff handles a situation when the useragent information is not available. This is important if someone decides to integrate our backtrace-browser library inside electron/react-native where the useragent is not available.

Detect missing information about the agent and fallback to the default

---

tools/cli/tsconfig.json
tsconfig.base.json

To allow for users with older versions of javascript to use our SDK

Updating target in base tsconfig to be es2015

---

packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts

For CLI tools such as our backtrace-js, the way how we try to read the application information is not good enough. Because of this, we cannot read the version/name and we throw an error on the startup. It's not bad, but we can do better. This diff allows to read __dirname and determine the path based on the __dirname

Bin starting path

---

package-lock.json
packages/node/package.json

This diff updates @backtrace-labs/node version to 0.0.2

NodeJS version update

---

package-lock.json
tools/cli/src/sourcemaps/upload.ts
tools/rollup-plugin/src/index.ts
tools/sourcemap-tools/package.json
tools/sourcemap-tools/src/SymbolUploader.ts
tools/sourcemap-tools/src/ZipArchive.ts
tools/sourcemap-tools/src/commands/archiveSourceMaps.ts
tools/sourcemap-tools/src/commands/processAndUploadAssetsCommand.ts
tools/sourcemap-tools/src/helpers/common.ts
tools/sourcemap-tools/tests/ZipArchive.spec.ts
tools/webpack-plugin/src/BacktracePlugin.ts

This PR fixes sourcemap uploads in cases of large files:
* `archiver` has been replaced with `tar` and `zlib`
* `.tar.gz` archives are now being output instead of `.zip` - confirmed that this works with the backend
* `pipe` to output (upload, archive file) is now being done before appending any sourcemaps.

cli: fix sourcemap upload issues

---

packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts

When creating a report using `BacktraceClient.send('message')`, there were some problems with stack frames:
* on V8, the first frame was being seen as "Error"
* in React there were some problems with async state machines being included in the report - removing `async` from `send` fixed the issue

sdk-core: fix skipping stack frame with message reports

---

packages/browser/README.md
packages/browser/src/attributes/UserIdentifierAttributeProvider.ts
packages/browser/src/builder/BacktraceClientBuilder.ts
packages/browser/tests/attributes/userIdAttributeProviderTests.spec.ts
packages/node/README.md
packages/node/src/attributes/ApplicationInformationAttributeProvider.ts
packages/node/src/builder/BacktraceClientBuilder.ts
packages/node/tests/attributes/applicationInformationAttributeProviderTests.spec.ts
packages/react/README.md
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/model/configuration/BacktraceConfiguration.ts
packages/sdk-core/src/modules/attribute/AttributeManager.ts
packages/sdk-core/src/modules/attribute/ClientAttributeProvider.ts
packages/sdk-core/src/modules/attribute/UserAttributeProvider.ts
packages/sdk-core/src/modules/data/BacktraceDataBuilder.ts
packages/sdk-core/tests/attributes/attributeManager.spec.ts
packages/sdk-core/tests/client/attributesTests.spec.ts
packages/sdk-core/tests/http/dataSerializationTests.spec.ts
packages/sdk-core/tests/metrics/summedEventTests.spec.ts
packages/sdk-core/tests/metrics/uniqueEventTests.spec.ts
packages/sdk-core/tests/report/dataGenerationTests.spec.ts

This PR adds a feature of deferred user attributes:
```ts
const client = BacktraceClient.initialize({
userAttributes: () => { "a": 123 }
});
client.addAttributes(() => { "b": 456 });
```
Additionally, it changes the way the attributes are applied. Before this PR, the static attributes were always overridden by dynamic attributes, no matter the order. Now, the attributes are applied in the order as they are added:
* attribute providers
* user attributes
* report attributes

add deferred user attributes

---

tools/cli/README.md
tools/cli/src/commands/Command.ts
tools/cli/src/helpers/common.ts
tools/cli/src/helpers/normalizePaths.ts
tools/cli/src/index.ts
tools/cli/src/logger.ts
tools/cli/src/options/loadOptions.ts
tools/cli/src/options/models/CliOptions.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/process.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts
tools/sourcemap-tools/src/SourceProcessor.ts

This PR adds `backtrace-js run` which works with `.backtracejsrc` to execute each command. It accepts some of the common parameters like `path`. The path has to always point to the source files - sourcemap files will be resolved from `sourceMappingURL`.

cli: add `run` command executing everything in one go

---

tools/cli/src/helpers/common.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/upload.ts
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/src/models/AsyncResult.ts

Currently `upload` and `add-sources` accept sourcemaps, which can be a bit misleading when using `process`, which accepts sources.
This PR allows for `upload` and `add-sources` to accept source files. CLI will try to resolve sourcemaps for given source files and continue as before:
```
> backtrace-js add-sources *.js
> backtrace-js process *.js
> backtrace-js upload *.js
> backtrace-js run *.js
```

cli: add possibility of specifying source files for upload and add-sources

---

package-lock.json
tools/sourcemap-tools/package.json
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/src/index.ts
tools/sourcemap-tools/src/models/RawSourceMap.ts
tools/sourcemap-tools/tests/SourceProcessor.spec.ts

This PR fixes two issues:
* `sourcesContent` array was out of sync with `sources` in offset sourcemap
* shebang occurrence erroneously offset sourcemap with additional line
Additionally, I realized that offsetting the sourcemap by lines is just prepending semicolons. This allowed me to simplify offsetting and move `source-map` to dev dependencies (still used for unit tests).

sourcemap tools: fix sourcemap invalid sourcesContent and shebang offset

---

package-lock.json
tools/cli/src/helpers/errorBehavior.ts
tools/cli/src/index.ts
tools/cli/src/logger.ts
tools/cli/src/options/loadOptions.ts
tools/cli/src/options/models/CliOptions.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/process.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts
tools/sourcemap-tools/package.json
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/src/index.ts
tools/sourcemap-tools/src/models/RawSourceMap.ts
tools/sourcemap-tools/tests/SourceProcessor.spec.ts

This diff adds `--asset-error-behavior` which can control what happens when an asset fails:
* `exit` - process exits with code 1 as soon as an asset fails. This is the default behavior,
* `skip` - the asset is skipped silently,
* `error`, `warn`, `info`, `debug`, `trace` - the asset error is logged under this log level.
Note that if assets fail, the process can still exit with error code 1 - for example, if none assets succeed in upload, the upload will fail because no files were supplied.

cli: add asset error behavior

---

packages/sdk-core/src/BacktraceCoreClient.ts

As people switch to the new Backtrace sdk, they may not make calls directly to `client.send()`. Instead, as I've experienced in a current migration, they may just need to wrap `client.send()` in an existing `reportError()` (or similar) function. In this case, the user would need to overload their function as well. I think it is a better user experience if we just have the two overloads as in most cases, a user will only send an Error or string (not a BacktraceReport) and won't have to overload their function at all.

Combining the error and string overloads in BacktraceCoreClient.send()

---

tools/cli/src/helpers/common.ts
tools/cli/tests/_files/not-linked-sourcemaps/entry1.js
tools/cli/tests/_files/not-linked-sourcemaps/entry1.js.map
tools/cli/tests/_files/not-linked-sourcemaps/entry2.js
tools/cli/tests/_files/not-linked-sourcemaps/entry2.js.map
tools/cli/tests/_files/processed-not-linked-sourcemaps/entry1.js
tools/cli/tests/_files/processed-not-linked-sourcemaps/entry1.js.map
tools/cli/tests/_files/processed-not-linked-sourcemaps/entry2.js
tools/cli/tests/_files/processed-not-linked-sourcemaps/entry2.js.map
tools/cli/tests/_helpers/testFiles.ts
tools/cli/tests/sourcemaps/add-sources.spec.ts
tools/cli/tests/sourcemaps/process.spec.ts
tools/cli/tests/sourcemaps/run.spec.ts
tools/cli/tests/sourcemaps/upload.spec.ts
tools/sourcemap-tools/src/SourceProcessor.ts

This PR adds the functionality of locating the sourcemap file when `//# sourceMappingURL` is missing.

cli: add finding sourcemap by {filename.js}.map

---

tools/cli/src/logger.ts
tools/cli/tests/sourcemaps/run.spec.ts
tools/sourcemap-tools/src/helpers/common.ts

This PR fixes tests and how they are run:
* a missing `await` was probably causing race conditions with some test runs
* logger no longer is spamming when set to silent
* errors should be more meaningful

cli: fix unit tests

---

package-lock.json
packages/browser/src/BacktraceClient.ts
packages/node/package.json
packages/node/src/BacktraceClient.ts
packages/react/package.json
packages/react/src/BacktraceClient.ts
packages/sdk-core/src/BacktraceCoreClient.ts

Right now each client implements how to deal with the Backtrace "instance". The code is redundant. In addition to that storing the instance in a library "instance" instead of globally for every other instance might create some weird issues - for example: The error boundary won't find an instance. 
This diff fixes the behavior and forces all clients to use one single instance.

Single client instance

---

packages/sdk-core/src/model/http/SubmissionUrlInformation.ts
packages/sdk-core/tests/http/submissionUrlGenerationTests.spec.ts

Most of the time our libraries need to send json reports - this is why submission URL class has helpers around a json format. However other our libraries like react-native or electron will need to use different URLs to submit different types of data - like minidumps or plcrashreporter crashes. 
This diff extends the submission URL class and allow to transform the URL to the plcrashreporter or minidump format

Native Submission URLs

---

package-lock.json
packages/browser/package.json
packages/node/package.json
packages/react/package.json
packages/sdk-core/package.json

This diff updates sdk-core package to version 0.0.4.
What's new? 
- addAttachment method
- native submission URL generator
- SDK attribute manager API
- small improvements/adjustements in the API

Sdk-Core release 0.0.4

---

packages/browser/src/builder/BacktraceClientBuilder.ts
packages/node/src/builder/BacktraceClientBuilder.ts
packages/react/src/builder/BacktraceReactClientBuilder.ts
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/common/Events.ts
packages/sdk-core/src/events/ReportEvents.ts
packages/sdk-core/src/modules/BacktraceModule.ts
packages/sdk-core/src/modules/BacktraceModules.ts
packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsFilteringOptionsTests.spec.ts
packages/sdk-core/tests/common/Events.spec.ts
packages/sdk-core/tests/database/databaseSetupTests.spec.ts
packages/sdk-core/tests/metrics/summedEventTests.spec.ts
packages/sdk-core/tests/metrics/uniqueEventTests.spec.ts
packages/sdk-core/tests/mocks/BacktraceTestClient.ts

This diff aims to reduce coupling between some modules and the core client. The main reason is to make the client less dependent on the external modules, which the client can function perfectly fine without.
* `Events` class was added, which is an event emitter similar to Node's `EventEmitter`, but not node-dependent,
* module map was added,
* database, metrics, breadcrumbs were moved to modules,
* database and breadcrumbs are no longer called by the client directly, but rather through Events.
Also moved `initialize` out of constructor and to the builders. The reason for that is to defer initialization of modules to after the class has been constructed.

add events and modules to core client

---

examples/sdk/node/.gitignore
examples/sdk/node/package-lock.json
examples/sdk/node/package.json
examples/sdk/node/src/index.ts
packages/node/webpack.config.js

This PR adds some improvements and fixes to node and node examples:
* node package will no longer contain source code in sourcemaps, and the sources will point to the original sources
* node example has now an option to add breadcrumb
* fix ignoring database directory in node example
* fix @backtrace-labs/node dependency in node example

node build and node example improvements

---

tools/cli/README.md
tools/cli/src/options/loadOptions.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts

This PR fixes some errors with CLI:
* bring back `subdomain` and `token` options
* display process and add-sources messages in run only if enabled
* fix loading config for subcommands
* fix dry-run and pass-with-no-files for upload
* update README

cli: various fixes

---

packages/node/src/BacktraceClient.ts
packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
packages/node/src/common/AlternatingFileWriter.ts
packages/node/tests/.gitignore
packages/node/tests/common/alternatingFile.spec.ts
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/index.ts
packages/sdk-core/src/model/configuration/BacktraceDatabaseConfiguration.ts
packages/sdk-core/src/modules/BacktraceModule.ts
packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
packages/sdk-core/src/modules/breadcrumbs/index.ts
packages/sdk-core/src/modules/breadcrumbs/storage/BreadcrumbsStorage.ts
packages/sdk-core/src/modules/breadcrumbs/storage/InMemoryBreadcrumbsStorage.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/storage/SessionFiles.ts
packages/sdk-core/src/modules/storage/index.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsFilteringOptionsTests.spec.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsInterceptorTests.spec.ts
packages/sdk-core/tests/storage/SessionFiles.spec.ts

This PR adds the functionality of storing breadcrumbs from previous session in database.
The way it works is with a new `SessionFiles` class, which manages all previous sessions. The sessions are cleared after initialization, however, a module may lock the session before to delay the clearing. After the module unlocks the session, it is cleared automatically. This helps to remove sessions that are not used by pending reports, and not to remove those that are used.
By default, the previous sessions are limited to 1. Meaning, that if more than one previous session is available, only the most recent one will be able to be locked.
The breadcrumbs are stored on disk as each line representing a JSON breadcrumb. It is not a JSON array. Two files are used to preserve breadcrumbs. After reaching …

node: breadcrumbs from previous session in database

---

examples/sdk/node/src/index.ts
packages/node/src/BacktraceClient.ts
packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/events/AttributeEvents.ts
packages/sdk-core/src/index.ts
packages/sdk-core/src/modules/BacktraceModule.ts
packages/sdk-core/src/modules/BacktraceModules.ts
packages/sdk-core/src/modules/attribute/AttributeManager.ts
packages/sdk-core/src/modules/attribute/FileAttributeManager.ts
packages/sdk-core/src/modules/attribute/index.ts

This PR adds attributes from previous session in native crashes:
* if database and native crashes are enabled, the attributes will be saved to disk,
* every time the scoped attributes change, attributes will be resaved,
* when loading native crashes, attributes from previous session will be also loaded.
Jira task: BT-586

node: attributes from previous session in native crashes

---

packages/browser/src/BacktraceClient.ts

When the error object is unavailable (for example script error), the backtrace report has a null as an error message. Instead we can fallback to the errorEvent message. With the error message users can detect/recognize errors like scripting errors). In addition to that, when the error object is not available (means the stack trace object is also empty) then we generate a stack trace based on current stack trace (including async frames). By removing async from the method we will avoid generating useless stack frames.

Error event fallback if the error object is not available

---

package-lock.json
packages/browser/package.json
packages/browser/src/redux/BacktraceReduxMiddleware.ts
packages/node/package.json
packages/react/package.json
packages/sdk-core/package.json

This fixes the bug where we don't handle circular references or bigints properly

Adding jsonEscaper to JSON.stringify() and not assuming action exists

---

package-lock.json
package.json
scripts/syncVersions.ts

This script helps to synchronize all versions of workspace packages in all workspaces.
For example, if `sdk-core` version changes, instead of going to every package and updating the version manually, one has to only run `npm run syncVersions` and it will take care of everything.
Example:
1. update sdk-core from 0.0.5 to 0.0.6
2. run `npm run syncVersions`
Output:
```
> @backtrace-labs/javascript@0.0.1 syncVersions
> ts-node ./scripts/syncVersions.ts
[@backtrace-labs/sdk-core] - no changes
[@backtrace-labs/browser] - updated @backtrace-labs/sdk-core from ^0.0.5 to ^0.0.6 in dependencies
[@backtrace-labs/react] - updated @backtrace-labs/sdk-core from ^0.0.5 to ^0.0.6 in dependencies
[@backtrace-labs/node] - updated @backtrace-labs/sdk-core from ^0.0.5 to ^0.0.6 in dependencies …
```

sync versions script

---

tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts
tools/sourcemap-tools/src/ZipArchive.ts
tools/sourcemap-tools/src/commands/loadSourceMaps.ts
tools/sourcemap-tools/src/commands/uploadArchive.ts
tools/sourcemap-tools/tests/ZipArchive.spec.ts

This PR hopefully fixes the random test failures.
After adding this change, running `npm run test --upload` 40 times succeeded every time.
Before the change, I was getting at least one failure per 20 runs.

cli: test and upload improvements

---

package-lock.json
package.json
scripts/README.md
scripts/common/commands.ts
scripts/common/git.ts
scripts/common/output.ts
scripts/common/packageJson.ts
scripts/common/transaction.ts
scripts/gitRelease.ts
scripts/release.ts
scripts/syncVersions.ts
tsconfig.json

This PR adds two scripts:
* gitRelease.ts - for a package, increments version, commits the version update to `<package>/<version>`
* release.ts - for a package, releases current version and creates a tag on HEAD or provided commit hash
Scripts have a rudimentary transaction capability - if something fails on the way, the script will try to undo all stuff it did.
sdk-core/0.0.7 was released using these scripts.

scripts: add scripts for making releases

---

packages/nestjs/README.md

Correct reference to @backtrace/node, which should be @backtrace/nestjs

Correct reference to @backtrace/node

---

packages/react-native/src/BacktraceClient.ts
packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
packages/sdk-core/tests/converters/stackTraceConverterTests.spec.ts
packages/sdk-core/tests/converters/v8stackTraceTestCases.ts

This diff adds better support for Hermes-specific stack trace - it's like v8 but before source code information there might be "address at" instead of "at" like in typical v8 stack trace.

Hermes react stack trace

---

tools/cli/src/helpers/common.ts
tools/cli/src/helpers/errorBehavior.ts
tools/cli/src/helpers/find.ts
tools/cli/src/helpers/logs.ts
tools/cli/src/models/Asset.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/process.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts
tools/cli/tests/_files/not-linked-different-name-sourcemaps/entry1.js
tools/cli/tests/_files/not-linked-different-name-sourcemaps/entry2.js
tools/cli/tests/_files/not-linked-different-name-sourcemaps/sourcemap1.js.map
tools/cli/tests/_files/not-linked-different-name-sourcemaps/sourcemap2.js.map
tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/entry1.js
tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/entry2.js
tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/sourcemap1.js.map
tools/cli/tests/_files/processed-not-linked-different-name-sourcemaps/sourcemap2.js.map
tools/cli/tests/_helpers/testFiles.ts
tools/cli/tests/sourcemaps/add-sources.spec.ts
tools/cli/tests/sourcemaps/process.spec.ts
tools/cli/tests/sourcemaps/run.spec.ts
tools/cli/tests/sourcemaps/upload.spec.ts
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/src/helpers/common.ts

This PR adds support of tuple paths for paths, so you can assign specific sourcemaps to sources.
For example:
```
$ backtrace-js process ./lib/index.js:./lib/sourcemap.js.map ./lib/file2.js:./lib/sourcemap2.js.map
```

cli: support tuple paths

---

packages/browser/src/redux/BacktraceReduxMiddleware.ts
packages/browser/tests/redux/backtraceReduxMiddlewareTests.spec.ts

Adds following modes to the Redux middleware:
* `all` - include everything by default,
* `omit-values` - add the breadcrumb, but omit the values,
* `off` - disable the middleware.
When `omit-values` is specified, only `type` is added to attributes.

browser: add middleware modes to redux middleware, move JSON action to attributes

---

packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
packages/sdk-core/tests/breadcrumbs/breadcrumbsCreationTests.spec.ts

We're in the javascript world. We should expect unexpected. In any logger integration, even if we expect to receive a string, logger can pass unstructured data. We expect string, but we should be prepared for the case when we receive unexpected input, that breaks things. This change makes sure the message passed by the logger or user is always valid or will be always converted into the format we want to have
refs: BT-1968

react-native: ensure breadcrumb message is always a string type

---

packages/react-native/src/breadcrumbs/events/AppStateBreadcrumbSubscriber.ts
packages/react-native/src/breadcrumbs/events/DimensionChangeBreadcrumbSubscriber.ts
packages/react-native/src/breadcrumbs/events/WebRequestEventSubscriber.ts
packages/react-native/src/builder/BacktraceClientBuilder.ts

This diff adds managed breadcrumbs support to the react-native library. Basic breadcrumbs are populated.
Side note:
- we want to avoid using react library inside react-native - builder includes our react/browser/sdk-core library in the bundler output. We want to reduce the size of the library since it matters a lot on mobile

react-native: managed breadcrumb support

---

tools/cli/src/helpers/errorBehavior.ts
tools/cli/src/helpers/logs.ts
tools/cli/src/sourcemaps/add-sources.ts
tools/cli/src/sourcemaps/process.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts
tools/cli/tests/sourcemaps/add-sources.spec.ts
tools/cli/tests/sourcemaps/run.spec.ts
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/tests/SourceProcessor.spec.ts

This PR adds some changes to add-sources:
* by default, it will now warn about sources that failed to add if the source is not there, and skip it if the source is already in the sourcemap,
* you can control what happens with failed sources using `--source-error-behavior`
* if `--force` is passed, all sources are treated as if they were not there
Jira task: BT-2080

cli: add-sources error behavior

---

packages/react-native/src/ReactNativeRequestHandler.ts

This diff adds a new header to the multipart upload request. Those headers are necessary to fix a problem with a truncated stream sent by react-native to the server. 
refs BT-1979

react-native: set transfer encoding to chunked

---

packages/sdk-core/src/modules/converter/V8StackTraceConverter.ts
packages/sdk-core/tests/converters/v8stackTraceTestCases.ts

We see more and more invalid frames generated by the sdk if the frame has:
* generic element (<anonymous>) 
* async keyword
This diff adds support to the two cases I mentioned above

sdk-core: Add support for async frames and generic params

---

packages/node/src/BacktraceNodeRequestHandler.ts

Due to invalid protocol check, we cannot send reports via HTTP. This pull request fixes this behavior and now we correctly compare the protocol

backtrace-node: Use https client only when the protocol is set to https:

---

examples/sdk/electron/package-lock.json
examples/sdk/node/package-lock.json
package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/electron/CHANGELOG.md
packages/electron/package.json
packages/nestjs/CHANGELOG.md
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json

This pull request updates all our libraries to version 0.3.0. What's new? 
-  the send method now returns a submission result,
- the node library will use a correct HTTP client depending on the protocol.

Version 0.3.0

---

packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
packages/sdk-core/src/dataStructures/index.ts
packages/sdk-core/src/index.ts

This PR exposes modules to public API.
We require this to extend client with plugins such as session replay.

sdk-core: add useModule to builder, export dataStructures

---

examples/sdk/browser/package.json
examples/sdk/browser/src/index.ts
package-lock.json
package.json
packages/sdk-core/src/builder/BacktraceCoreClientBuilder.ts
packages/sdk-core/src/dataStructures/index.ts
packages/sdk-core/src/index.ts
packages/session-replay/LICENSE
packages/session-replay/package.json
packages/session-replay/src/BacktraceSessionRecorder.ts
packages/session-replay/src/BacktraceSessionReplayModule.ts
packages/session-replay/src/index.ts
packages/session-replay/src/options.ts
packages/session-replay/tsconfig.json
packages/session-replay/webpack.config.js

This PR adds the session replay package, which enables us to attach session replays to reports sent to Backtrace.
See JSDocs and browser example for usage exampels.

session-replay: add session replay package

---

packages/react-native/ios/BacktraceCpuAttributeProvider.mm
packages/react-native/ios/BacktraceMemoryUsageAttributeProvider.mm

We found invalid attribute names while we were reviewing library attributes. This diff fixes attribute map for react-native on ios

react-native: Attribute map - fixed attribute names for react-native

---

packages/sdk-core/src/modules/database/BacktraceDatabase.ts

We want to exit fast when there is no reason to process reports. This diff allows to exit from the database send method when the database is disabled (for example: via dispose method)

Exit on disabled database

---

packages/browser/src/BacktraceBrowserRequestHandler.ts
packages/node/src/BacktraceNodeRequestHandler.ts
packages/react-native/src/ReactNativeRequestHandler.ts

This pull request adds a transfer encoding header to javascript submission layers.

Use transfer encoding header

---

package-lock.json
packages/node/package.json
packages/node/src/attributes/MachineIdentitfierAttributeProvider.ts

This change removes the `native-reg` dependency from `node` SDK.
This should fix some errors with rebuilding native dependencies on Electron.

node: replace native-reg with call to reg query

---

package-lock.json
packages/node/CHANGELOG.md
packages/node/package.json

-   remove `native-reg` and use `reg query` executable to determine Windows machine GUID (#250)

node: version 0.3.2

---

package-lock.json
packages/electron/CHANGELOG.md
packages/electron/package.json

-   update `@backtrace/node` to `0.3.2`

electron: version 0.3.1

---

examples/sdk/browser/package-lock.json
examples/sdk/browser/package.json
package-lock.json
packages/session-replay/package.json
packages/session-replay/src/BacktraceSessionRecorder.ts
packages/session-replay/src/options.ts

This PR adds the following:
* update `rrweb` to `2.0.0-alpha-15`
* use `OverwritingArray` with `_previousEvents` to fix `isCheckout` error
* remove `maxTime` - the behavior can be misleading in this case, user can always use `checkoutEveryNms` from advanced options
* when buffer is full, send always `_maxEventCount` events, no less, no more

session-replay: update rrweb and implement fixes

---

examples/sdk/browser/index.html
package-lock.json
packages/session-replay/jest.config.js
packages/session-replay/package.json
packages/session-replay/src/BacktraceSessionRecorder.ts
packages/session-replay/src/options.ts
packages/session-replay/src/privacy/maskTextFn.ts
packages/session-replay/tests/privacy/maskTextFn.spec.ts

This PR adds the following:
* pass privacy options to `rrweb` settings,
* mask all inputs by default,
* add input to browser example to demonstrate masking.

session-replay: PII defaults

---

examples/sdk/electron/package-lock.json
packages/electron/src/main/modules/BacktraceMainElectronModule.ts

This diff adds support for the error.type attribute for electron crashes. 
ref: BT-3057

Add support for error.type for electron crashes

---

packages/sdk-core/src/BacktraceCoreClient.ts

When `BacktraceBuilder` is used, despite it calling `initialize`, the global instance is not set, leading to errors in React's `ErrorBoundary`.
This change fixes that by setting the instance in `sdk-core`'s `BacktraceCoreClient`.

sdk-core: fix missing instance when builder is used

---

package-lock.json
packages/session-replay/CHANGELOG.md
packages/session-replay/package.json

-   output ES and CJS modules (#272)
-   bundle `rrweb` in the library (#272)

session-replay: version 0.1.1

---

package-lock.json
packages/browser/src/BacktraceBrowserSessionProvider.ts
packages/browser/src/attributes/WebsiteAttributeProvider.ts
packages/browser/tests/metrics/persistentSessionProviderTests.spec.ts
packages/sdk-core/jest.config.js
packages/sdk-core/jest.config.mjs
packages/sdk-core/jest.setup.mjs
packages/sdk-core/package.json
packages/sdk-core/rollup.config.mjs
packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts
packages/sdk-core/tests/database/databaseContextMemoryStorageTests.spec.ts
packages/sdk-core/tests/database/databaseContextValidationTests.spec.ts
packages/sdk-core/tests/database/databaseRecordBatchTests.spec.ts
packages/sdk-core/tests/database/databaseSendTests.spec.ts
packages/sdk-core/tests/database/databaseStorageFlowTests.spec.ts
packages/sdk-core/tsconfig.build.json
packages/sdk-core/tsconfig.json

This PR adds ESM module support to `sdk-core`.
`sdk-core` is now bundled into two files:
- `bundle.mjs` - ESM modules
- `bundle.cjs` - CommomJS (Node) modules

sdk-core: use ESM modules

---

packages/browser/src/BacktraceBrowserRequestHandler.ts
packages/react-native/src/ReactNativeRequestHandler.ts
packages/sdk-core/src/common/AbortController.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/metrics/MetricsSubmissionQueue.ts
packages/session-replay/package.json

Every time `anySignal` is used, an `abort` event is added to the passed `AbortSignal`.
If the signal is not cancelled, the event is not removed. If the code using `anySignal` is executed multiple times, this can cause events to build up without being cleaned up.
This PR changes this and introduces a function `disposeSignal` that cleans up the signal afterwards.

sdk-core, browser, react-native: fix abort event not being removed from signal

---

package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/react/package.json

-   update `@backtrace/sdk-core` to `0.5.0`
-   update code to use ES modules (#268, #279)
-   emit CJS and ES modules (#268, #279)
-   fix abort event not being removed from signal (#265)

browser: version 0.4.0

---

package-lock.json
packages/react/CHANGELOG.md
packages/react/package.json

-   update `@backtrace/browser` to `0.4.0`
-   update code to use ES modules (#269, #279)
-   emit CJS and ES modules (#269, #279)

react: version 0.4.0

---

package-lock.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json

-   update `@backtrace/sdk-core` to `0.5.0`
-   update code to use ES modules (#267, #279)
-   emit CJS and ES modules (#267, #279)

node: version 0.5.0

---

package-lock.json
packages/electron/CHANGELOG.md
packages/electron/package.json

-   update `@backtrace/node` to `0.5.0`
-   update code to use ES modules (#270, #279)
-   emit CJS and ES modules (#270, #279)

electron: version 0.5.0

---

packages/nestjs/rollup.config.mjs

Rollup configuration caused `tslib` to be excluded from bundle, having it be imported from `node_modules`. On top of that, the import path was absolute, which caused import errors on other machines.
This fixes the configuration so required `tslib` functions are bundled with the code.

nestjs: include tslib in code instead of externalizing it

---

package-lock.json
packages/nestjs/CHANGELOG.md
packages/nestjs/package.json

-   fix imports of `tslib` - internalize `tslib` functions (#288)

nestjs: version 0.4.1

---

packages/sdk-core/src/common/intervalHelper.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/metrics/BacktraceMetrics.ts

**Why**
This pull request allows to unref a timeout object created by the setInerval function. By doing that we can easily exit a node process, without waiting on the background process work to finish.

sdk-core: unref setinterval

---

packages/sdk-core/src/BacktraceCoreClient.ts
packages/sdk-core/src/common/Events.ts
packages/sdk-core/src/events/AttachmentEvents.ts
packages/sdk-core/src/events/AttributeEvents.ts
packages/sdk-core/src/events/ClientEvents.ts
packages/sdk-core/src/modules/BacktraceModule.ts
packages/sdk-core/src/modules/breadcrumbs/BreadcrumbsManager.ts
packages/sdk-core/src/modules/database/BacktraceDatabase.ts
packages/sdk-core/src/modules/database/BacktraceDatabaseEvents.ts
packages/sdk-core/src/modules/storage/SessionFiles.ts
packages/sdk-core/tests/mocks/testHttpClient.ts

This PR adds event support for client directly.
You can attach to `before-skip`, `before-send`, and `after-send` events on client instance:
```typescript
const client = BacktraceClient.initialize({ ... });
client.on('after-send', (report, data, attachments, result) => { ... });
```
This is required for me to use in smoketests, so I know if `after-send` is executed after e.g. an exception is thrown.
`BacktraceDatabase` now emits events of it's own:
```ts
type BacktraceDatabaseEvents = {
added: [record: BacktraceDatabaseRecord];
removed: [record: BacktraceDatabaseRecord];
'before-send': [record: BacktraceDatabaseRecord];
'after-send': [
record: BacktraceDatabaseRecord,
result: BacktraceReportSubmissionResult<BacktraceSubmissionResponse>,
];
};
```

sdk-core: use core client as event emitter, send reports from database via client

---

package-lock.json
packages/browser/package.json
packages/node/package.json
packages/react-native/package.json
packages/react/package.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json
packages/session-replay/package.json

-   add `setInterval` unreffing, fixing blocking of application exit (#291)
-   reduce breadcrumbs size (#228)
-   use core client as event emitter (#290)
-   sdk-core, node: attribute validation (#296)

sdk-core: version 0.6.0

---

package-lock.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json

-   update `@backtrace/sdk-core` to `0.6.0`
-   reduce breadcrumbs size (#228)
-   use `application` and `application.version` attribute validation from `sdk-core` (#296)

node: version 0.6.0

---

package-lock.json
packages/electron/CHANGELOG.md
packages/electron/package.json

-   update `@backtrace/node` to `0.6.0`
-   reduce breadcrumb size (#231)

electron: version 0.6.0

---

packages/nestjs/README.md
packages/nestjs/src/backtrace.filter.ts
packages/nestjs/src/backtrace.handler.ts
packages/nestjs/src/backtrace.interceptor.ts
packages/nestjs/src/backtrace.module.ts
packages/nestjs/src/index.ts
packages/nestjs/tests/backtrace.filter.e2e.spec.ts
packages/nestjs/tests/backtrace.handler.spec.ts
packages/nestjs/tests/backtrace.interceptor.e2e.spec.ts
packages/nestjs/tests/backtrace.interceptor.spec.ts

This PR adds `BacktraceExceptionFilter` and `BacktraceExceptionHandler`.
The filter allows to catch more exceptions than previously possible with `BacktraceInterceptor`.
The handler allows to use the exception handling logic in own code.

nestjs: add exception filter and exception handler

---

packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts
packages/node/tests/breadcrumbs/FileBreadcrumbsStorage.spec.ts

The breadcrumb name was set to file path, resulting in UI not being able to pick up the breadcrumbs.
This PR fixes the issue.

node: fix invalid breadcrumb name in FileBreadcrumbsStorage

---

package-lock.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json

-   fix invalid breadcrumb name in `FileBreadcrumbsStorage` (#303)

node: version 0.6.1

---

packages/react-native/android/src/main/java/backtrace/library/BacktraceDirectoryProvider.java
packages/react-native/src/BacktraceClient.ts

This PR fixes previous sessions not being cleared, even if they are not locked.
The reasons were:
* Android implementation of `readDirSync` returned full paths instead of file names (suprisingly, asynchronous `readDir` is implemented correctly)
* previous sessions were not unlocked when error was not thrown in `BacktraceClient.initialize` (replaced `catch` with `finally`

react-native: fix previous sessions not being cleared

---

packages/react-native/ios/BacktraceReactNative.mm

This PR returns `nil` instead of `instance` from `BacktraceReactNative.initialize`, as the `instance` object was impossible to serialize to JSON.
https://reactnative.dev/docs/0.70/native-modules-ios#synchronous-methods
>The return type of this method must be of object type (id) and should be serializable to JSON. This means that the hook can only return nil or JSON values (e.g. NSNumber, NSString, NSArray, NSDictionary).

react-native: fix invalid RN object returned from iOS BacktraceReactNative.initialize function

---

packages/react-native/ios/BacktraceApplicationAttributeProvider.h
packages/react-native/ios/BacktraceCpuAttributeProvider.h
packages/react-native/ios/BacktraceDeviceAttributeProvider.h
packages/react-native/ios/BacktraceDirectoryProvider.h
packages/react-native/ios/BacktraceFileSystemProvider.h
packages/react-native/ios/BacktraceMemoryUsageAttributeProvider.h
packages/react-native/ios/BacktraceReactNative.h
packages/react-native/ios/BacktraceSystemAttributeProvider.h
packages/react-native/ios/StreamWriter.h

This PR removes invalid imports in iOS headers for new architecture, causing build errors when switching to new architecture.

react-native: remove invalid imports from iOS headers

---

packages/nestjs/src/backtrace.module.ts
packages/nestjs/tests/backtrace.handler.spec.ts
packages/nestjs/tests/backtrace.module.spec.ts

This PR fixes the bug that caused an error to be thrown when registering `BacktraceModule` if the instance was uninitialized, regardless of the `skipIfClientUndefined` setting.

nestjs: fix skipIfClientUndefined not working in BacktraceModule

---

package-lock.json
packages/nestjs/CHANGELOG.md
packages/nestjs/package.json

-   fix `skipIfClientUndefined` not working in `BacktraceModule` (#309)

nestjs: version 0.5.1

---

packages/electron/package.json

Our customers keep asking us to bump the electron version. This pull request requires a minimal electron version instead of us manually updating the maximum electron version.

electron: change default electron version to the latest

---

package-lock.json
packages/electron/CHANGELOG.md
packages/electron/package.json

-   update `@backtrace/node` to `0.6.1`
-   change the default electron version to the latest (#311)

electron: version 0.6.1

---

packages/browser/package.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/package.json
packages/react-native/package.json
packages/react/package.json
packages/sdk-core/package.json
packages/session-replay/package.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/sourcemap-tools/package.json
tools/vite-plugin/package.json
tools/webpack-plugin/package.json

This PR makes sure that all our packages have valid `prepublishOnly` scripts that:
1. build dependencies (run dependencies' `prepublishOnly` scripts),
2. clean package,
3. build package.

all: clean and build dependencies in prepublishOnly scripts (NFC)

---

package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/react/package.json

-   fix old `@backtrace/sdk-core` bundled with the package

browser: version 0.4.1

---

.husky/commit-msg
.husky/pre-commit
.husky/scripts/commit-msg.js
package-lock.json
package.json

This PR adds two commit hooks:
* `pre-commit` - formats all modified files using `prettier` and lints them using `eslint`
* `commit-msg` - checks if the commit message adheres to `prefix: message` format

repo: add commit hooks

---

CONTRIBUTING.md

This PR adds a `CONTRIBUTING.md` document describing our requirements and needs for contributing to the project.
Generated with https://generator.contributing.md/, then adopted to our repository.

repo: add CONTRIBUTING.md document

---

package-lock.json
packages/browser/package.json
packages/react/package.json
packages/session-replay/package.json
scripts/syncVersions.ts

As bundling removed the requirement of installing `@backtrace/*` dependencies, they have been moved to dev deps. However, this broke typings in packages that do not install dependent packages.
To mitigate this, these packages have been moved to normal dependencies. As the bundle will have a specific version, this specific is used in `package.json`. `syncVersions.ts` script has also been updated to not include `^` caret in version range by default, but rather preserve the operator, whatever it may be.

browser, react, session-replay: move @backtrace/* dependencies to normal dependencies (NFC)

---

package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/react/package.json

-   add `@backtrace/sdk-core` as normal dependency to fix typings

browser: version 0.4.2

---

packages/react-native/src/BacktraceClient.ts
packages/react-native/src/attachment/BacktraceFileAttachment.ts
packages/react-native/src/breadcrumbs/FileBreadcrumbsStorage.ts
packages/react-native/src/storage/combinedChunkSplitter.ts
packages/react-native/src/storage/lengthChunkSplitter.ts
packages/react-native/tests/storage/FileBreadcrumbsStorage.spec.ts
packages/react-native/tests/storage/lengthChunkSplitter.spec.ts
packages/react-native/tests/storage/lineChunkSplitter.spec.ts

Follow up to https://github.com/backtrace-labs/backtrace-javascript/pull/228 for React Native.
This uses the new breadcrumb writers implemented in https://github.com/backtrace-labs/backtrace-javascript/pull/315.

react-native: reduce breadcrumb size

---

packages/node/src/streams/fileChunkSink.ts

This PR fixes an error when trying to delete a non-existent breadcrumb file.

node: fix invalid error handler in fileChunkSink

---

package-lock.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json

-   fix invalid error handler in `fileChunkSink` (#322)

node: version 0.6.2

---

examples/sdk/reactNative/ios-hermesc.sh
examples/sdk/reactNative/ios-sourcemaps.sh
examples/sdk/reactNative/ios/reactNative.xcodeproj/project.pbxproj
examples/sdk/reactNative/ios/reactNative.xcodeproj/xcshareddata/xcschemes/reactNative.xcscheme
examples/sdk/reactNative/package-lock.json
examples/sdk/reactNative/package.json

This PR fixes the React Native example sourcemap processing and upload for iOS builds.

react-native example: fix sourcemap support on iOS

---

smoketests/packages/react-ts-esm/package.json

This pull request downgrades the react-dom types library to the one, that we use in the SDK package.json

smoketest: Downgrade react types in smoketests to the version in the sdk

---

packages/react-native/src/builder/BacktraceClientBuilder.ts
packages/react-native/src/common/DebuggerHelper.ts
packages/react-native/src/crashReporter/CrashReporter.ts
packages/react-native/src/handlers/android/AndroidUnhandledExceptionHandler.ts

This pull request enables native functions for bridgeless react-native setup. In the bridgeless setup, we know we can run native functions.  
Now all native functions such us unhandled exceptions/crashes are working in the bridgeless mode.
ref: BT-5152,  BT-5174

react-native: Enable native functions for Bridgeless react-native setup

---

.github/workflows/test.yml

We keep running the cicd pipeline after we commit more changes. Some pipelines are already long - so canceling them makes a lot of sense. This pull request cancels a cicd pipeline on a new change added to the pull request

cicd: cancel previous workflow on commit

---

examples/sdk/reactNative/android/app/src/main/java/com/reactnative/MainApplication.java
examples/sdk/reactNative/index.js

Changing gradle.properties to run the app in the bridgeless mode, crashed the example app. This pull request:
- fix mainapplication in the bridgeless mode,
- Formats Android file with Android studio formatter

react-native: add support for bridgeless mode in the android example

---

packages/electron/src/main/attributes/GpuAttributeProvider.ts

This fixes an issue with `gpu-info-update` being emitted repeatedly after `getGPUInfo` is called, causing a loop.
We now only listen on this event once. It is unlikely that the GPU info will change within the app runtime.
https://github.com/electron/electron/issues/30827

electron: fix potential loop with gpu-info-update

---

package-lock.json
packages/electron/CHANGELOG.md
packages/electron/package.json

-   update `@backtrace/node` to `0.6.2`
-   fix potential loop with gpu-info-update (#330)

electron: version 0.6.2

---

tools/sourcemap-tools/src/SourceProcessor.ts

This change exposes an option in the sourcemap-tools to process source maps via translation process (for example: via metro in react-native) 
ref: BT-5175

sourcemap-tools: add processSource to SourceProcessor

---

package-lock.json
packages/react-native/CHANGELOG.md
packages/react-native/package.json

-   update `@backtrace/sdk-core` to `0.6.0`
-   android crash handler upgrade (#301)
-   fix previous sessions not being cleared (#306)
-   fix invalid RN object returned from iOS BacktraceReactNative.initialize function (#308)
-   remove invalid imports from iOS headers (#307)
-   replace AlternatingFileWriter with WritableStream and ChunkifierSink for breadcrumbs (#315)
-   reduce breadcrumb size (#320)
-   fixed debugger detection in the bridgeless mode (#325)

react-native: version 0.2.0

---

package-lock.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/sourcemap-tools/CHANGELOG.md
tools/sourcemap-tools/package.json
tools/webpack-plugin/package.json

-   expose processSource for CLI tools (#332)

sourcemap-tools: version 0.2.4

---

package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/react/package.json

-   update `@backtrace/sdk-core` to `0.7.0`
-   add `BacktraceApi` (#335)

browser: version 0.5.0
