package-lock.json
packages/node/jest.config.js
packages/node/jest.setup.js
packages/node/package.json
packages/node/src/BacktraceNodeRequestHandler.ts
packages/node/src/agentDefinition.ts
packages/node/src/attachment/index.ts
packages/node/src/attributes/ProcessStatusAttributeProvider.ts
packages/node/src/index.ts
packages/node/webpack.config.js
tsconfig.json
tsconfig.packages.json

Compiles node package with Webpack.
This also adds the agent variables replacement.

Add Webpack to the node package

---

examples/sdk/browser/index.css
examples/sdk/browser/index.html
examples/sdk/browser/package-lock.json
examples/sdk/browser/package.json
examples/sdk/browser/src/consts.ts
examples/sdk/browser/src/index.ts
examples/sdk/browser/tsconfig.json
examples/sdk/browser/webpack.config.js

This diff adds a browser example - By using it we can send errors/messages to Backtrace.

Browser example

---

package-lock.json
tools/vite-plugin/.gitignore
tools/vite-plugin/LICENSE
tools/vite-plugin/package.json
tools/vite-plugin/src/index.ts
tools/vite-plugin/tsconfig.build.json
tools/vite-plugin/tsconfig.json
tools/vite-plugin/vite.config.js

Vite is just Rollup with extras. So the plugin is just a re-export of the Rollup plugin.

vite plugin based on rollup

---

tools/cli/src/sourcemaps/upload.ts

Add additional options for uploading.

cli: add subdomain and token options to upload

---

packages/browser/package.json
packages/node/package.json
packages/react/package.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/vite-plugin/package.json
tools/webpack-plugin/package.json

This diff prepares our packages for internal/external release

Release setup

---

.npmrc
package-lock.json
packages/node/package.json
packages/sdk-core/package.json

This diff adjusts package.json/package-lock.json and prepare libraries for the internal release.

Release files

---

packages/browser/README.md

- Pushed up the mention of source maps
- Pushed up the detail on what is sent by default
- Push down details on how to manually send
- Expanded some verbal descriptions

Fit 'n finish

---

packages/react/README.md

The only difference between this one and the browser readme is I updated all references of browser to react and added an Error Boundary section.

Adding react README.md

---

tools/sourcemap-tools/README.md

This diff contains the basic source map tool readme

Source map tools README

---

packages/sdk-core/README.md

This diff contains the basic readme file for the SDK core package

SDK Core README

---

packages/browser/README.md
packages/node/README.md
packages/react/README.md

This diff updates README.md with a new available API/adjustments to the breadcrumb docs

Client docs update

---

package-lock.json
packages/browser/package.json

This diff updates the browser package to version 0.0.2

Browser update 0.0.2

---

package-lock.json
packages/react/package.json

This diff updates the react library to version 0.0.2

React update 0.0.2

---

package-lock.json
packages/sdk-core/package.json

SDK-core 0.0.3 release

---

package-lock.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/webpack-plugin/package.json

This diff updates CLI package to version 0.0.2

Release: CLI 0.0.2

---

package-lock.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/sourcemap-tools/package.json
tools/webpack-plugin/package.json

This diff updates source map tools to version 0.0.2

Source map tools 0.0.2

---

package-lock.json
tools/cli/package.json
tools/sourcemap-tools/package.json

Source map 0.0.3 release

---

tools/cli/src/helpers/common.ts
tools/cli/src/sourcemaps/run.ts
tools/cli/src/sourcemaps/upload.ts

This PR removes duplicates in assets by debugId before passing them to upload.

cli: remove duplicate debugIds before uploading

---

package-lock.json
tools/cli/package.json
tools/rollup-plugin/package.json
tools/sourcemap-tools/package.json
tools/vite-plugin/package.json
tools/webpack-plugin/package.json

This diff updates all our CLI packages to use the newest version of the source code utilities.

CLI Release

---

examples/sdk/react/.backtracejsrc
examples/sdk/react/README.md
examples/sdk/react/package.json

Updating the react example app to have sourcemap / source code support.
I'm not sure the best way to guide the user for their upload url. All feedback is appreciated.

Adding sourcemap support to react example

---

package-lock.json
packages/node/package.json

Backtrace node 0.0.4 release
Changelog:
- general API improvements

Node release 0.0.4

---

package-lock.json
packages/react/package.json

Backtrace react 0.0.4 release
Changelog:
- general API improvements
- exposed stack trace parser and data builder
- Error boundary fallback function support

React release 0.0.4

---

packages/sdk-core/src/model/http/SubmissionUrlInformation.ts

React-Native cannot use the URL API. Unfortunately, most of the method available in the URL interface is unavailable (except some of them). Since the SubmissionUrl API is easy to implement manually, we can avoid using URL and use manual string manipulation to construct the URL.
This diff adjust the SubmissionUrl class to be re-usable in all our libraries

Do not use unsupported URL API in the react-native API

---

packages/node/src/breadcrumbs/FileBreadcrumbsStorage.ts

This diffs adds attributes to breadcrumb

node: Add breadcrumb attribute to the file

---

.vscode/launch.json
examples/sdk/electron/.gitignore
examples/sdk/electron/assets/index.css
examples/sdk/electron/assets/index.html
examples/sdk/electron/package-lock.json
examples/sdk/electron/package.json
examples/sdk/electron/src/common/MainApi.ts
examples/sdk/electron/src/main/consts.ts
examples/sdk/electron/src/main/index.ts
examples/sdk/electron/src/main/preload.ts
examples/sdk/electron/src/renderer/index.ts
examples/sdk/electron/tsconfig.json
examples/sdk/electron/tsconfig.main.json
examples/sdk/electron/tsconfig.renderer.json
examples/sdk/electron/webpack.config.js

This PR adds an example showcasing features of Backtrace in Electron, and how to initialize it in an Electron app.
Jira task: BT-709

electron example: add an example for using Electron SDK

---

packages/electron/src/main/BacktraceClient.ts
packages/electron/src/main/attributes/AllWindowsAttributeProvider.ts
packages/electron/src/main/attributes/NetAttributeProvider.ts
packages/electron/src/main/attributes/ScreenAttributeProvider.ts
packages/electron/src/main/attributes/WindowAttributeProvider.ts
packages/electron/src/main/attributes/helpers/attributes.ts
packages/electron/src/main/builder/BacktraceClientBuilder.ts
packages/electron/src/main/modules/BacktraceMainElectronModule.ts

This PR adds attributes from:
* available `BrowserWindow`s,
* `screen` - available displays,
* `net` - `isOnline`.
Jira task: BT-775

electron: add additional attributes to main crashes

---

packages/electron/src/main/attributes/helpers/attributes.ts
packages/electron/src/main/breadcrumbs/WindowEventSubscriber.ts
packages/electron/src/main/builder/BacktraceClientBuilder.ts

This PR adds multiple new breadcrumbs to Electron main process.
Jira task: BT-776

electron: add breadcrumbs

---

README.md

Package links pointed to browser. Corrected, and added nestjs and electron.

Update package links in base readme

---

package-lock.json
tools/cli/package.json
tools/cli/src/sourcemaps/run.ts

Fix ignoring `include-sources` in `run`.

cli: version 0.2.1

---

tools/sourcemap-tools/src/DebugIdGenerator.ts

This diff adds globalThis support to debugIdGenerator.
refs: BT-761

Source map global this

---

package-lock.json
tools/cli/jest.config.js
tools/cli/package.json
tools/cli/src/sourcemaps/process.ts
tools/cli/tests/_files/processed-sourcemaps/entry1.js
tools/cli/tests/_files/processed-sourcemaps/entry1.js.map
tools/cli/tests/_files/processed-sourcemaps/entry2.js
tools/cli/tests/_files/processed-sourcemaps/entry2.js.map
tools/cli/tests/_files/processed-sources/entry1.js
tools/cli/tests/_files/processed-sources/entry1.js.map
tools/cli/tests/_files/processed-sources/entry2.js
tools/cli/tests/_files/processed-sources/entry2.js.map
tools/cli/tests/_helpers/testFiles.ts
tools/cli/tests/setup.ts
tools/cli/tests/sourcemaps/process.spec.ts
tools/sourcemap-tools/src/DebugIdGenerator.ts
tools/sourcemap-tools/src/SourceProcessor.ts
tools/sourcemap-tools/tests/SourceProcessor.spec.ts

This PR adds partial processing of source/sourcemap files.
If source has a debug ID and the sourcemap does not, the debug ID from the source is copied to the sourcemap.

cli: partial processing

---

package-lock.json
tools/sourcemap-tools/package.json

* sourcemap-tools: replace flatmap with reduce implementation
* sourcemap tools: add replacing debug ID and not modyfing source when it has debug ID already

sourcemap-tools: version 0.2.1

---

examples/sdk/node/src/index.ts
packages/sdk-core/src/BacktraceCoreClient.ts

This pull request allows destroying the instance of the client via dispose method.

sdk-core: Destroy client on dispose

---

package-lock.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json

Sdk-core: Changelog update

---

packages/browser/CHANGELOG.md
packages/browser/package.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json
packages/react-native/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json
packages/session-replay/package.json

This pull request updates all our libraries versions

Release 0.3.2

---

tools/cli/tests/_helpers/testFiles.ts

Tests are failing probably due to some strange race condition, which doesn't affect anything in runtime.
I opted to just retry removing files.

cli: add retry to removing files after test

---

package-lock.json
packages/browser/package.json
packages/node/package.json
packages/react-native/package.json
packages/react/package.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json
packages/session-replay/package.json

-   update code to use ES modules (#266, #279)
-   emit CJS and ES modules (#266, #279)
-   fix abort event not being removed from signal (#265)

sdk-core: version 0.5.0

---

package-lock.json
packages/session-replay/CHANGELOG.md
packages/session-replay/package.json

-   fix ES and CJS issues (#279)

session-replay: version 0.2.0

---

packages/electron/src/main/modules/BacktraceMainElectronModule.ts
packages/electron/src/renderer/addBacktraceElectron.ts
packages/electron/src/renderer/modules/IpcBreadcrumbsStorage.ts

Follow up to https://github.com/backtrace-labs/backtrace-javascript/pull/228 for Electron.

electron: reduce breadcrumb size

---

package-lock.json
packages/nestjs/CHANGELOG.md
packages/nestjs/package.json

-   update `@backtrace/node` to `0.6.0`
-   add exception filter and exception handler (#293)

nestjs: version 0.5.0

---

package-lock.json
packages/react/CHANGELOG.md
packages/react/package.json

-   add `@backtrace/browser` as normal dependency to fix typings

react: version 0.4.1

---

package-lock.json
packages/electron/package.json
packages/nestjs/package.json
packages/node/CHANGELOG.md
packages/node/package.json

-   update `@backtrace/sdk-core` to `0.7.0`
-   add `BacktraceApi` (#335)

node: version 0.7.0

---

package-lock.json
packages/browser/package.json
packages/node/package.json
packages/react-native/package.json
packages/sdk-core/CHANGELOG.md
packages/sdk-core/package.json
packages/session-replay/package.json

-   fix endless loop when loading SessionFiles (#347)

sdk-core: version 0.8.0

---

package-lock.json
packages/browser/CHANGELOG.md
packages/browser/package.json
packages/react/package.json

-   update `@backtrace/sdk-core` to `0.8.0`
-   add `BrowserFileSystem` based on localStorage (#348)

browser: version 0.6.0
